name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        include:
          - os: macos-latest
            python: "3.11"
          - os: windows-latest
            python: "3.11"
    name: Python ${{ matrix.python }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install coverage tox
      - run: python -m tox
      - uses: codecov/codecov-action@v3
        with:
          name: ${{ matrix.python }} on ${{ matrix.os }}
